### ISSUE TITLE
1.12.2版本自制整合包，在放下豆腐聚合器（服务器上放下即崩，本地客户端测试时放下后对其右键才会崩溃）时会发生崩溃，经测试与深渊国度mod有关

### ISSUE THREAD

**Issue by gabrielysx** [0999312/TofuCraftReload#102]
#### MOD版本 - Mod version:

0.1.0.8

#### Forge版本 - Forge version:

14.23.5.2854

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

单机与多人游戏服务器都存在此问题

#### 完整的MOD列表 - Installed mods:

![](在此处填入你的截图链接，没有截图请删除此行 Paste your screenshot link here, or delete this line)
经测试，在仅存在本mod与1.10.2版本的深渊国度mod（AbyssalCraft-1.12.2-1.10.2.jar）（和相关前置mod）时会发生崩溃
mod列表：
MMLib-1.5.0
AbyssalCraft-1.12.2-1.10.2
TofuCraftReload-0.1.0.8
## 崩溃报告的链接 - Link to full crash log

https://paste.ubuntu.com/p/73sztfx86y/

#### 产生Bug的步骤 - How to reproduce:

1.拿出一个豆腐聚合器，放下
2.对其右键（在服务器上无需右键，放下时就会崩溃）
3. etc...

**Comment by TCreopargh** [comment]
+1,同样的问题
https://paste.ubuntu.com/p/GnrzsdcJbw/

**Comment by 0999312** [comment]
请直接联系深渊国度Mod开发团队。
