### ISSUE TITLE
[1.12.2] MMLib 2.0.0 不兼容问题

### ISSUE THREAD

**Issue by TCreopargh** [0999312/TofuCraftReload#103]
#### MOD版本 - Mod version:

0.1.0.8

#### Forge版本 - Forge version:

2854

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

单人

#### 完整的MOD列表 - Installed mods:

见崩溃报告

## 崩溃报告的链接 - Link to full crash log

https://paste.ubuntu.com/p/7vTBQDPCST/

## 问题描述 - Description of the problem

1.12.2 MMLib的最新版似乎与豆腐craft现在的最新版不兼容，这个问题只在今天更新了MMLib之后出现，回退MMLib版本后问题解决

#### 产生Bug的步骤 - How to reproduce:

1. 安装MMLib2.0.0
2. 安装1.12豆腐craft 0.1.0.8
3. crash！

**Comment by 0999312** [comment]
2.0.0适配的版本正在更新中！
