### ISSUE TITLE
盐卤右键消失

### ISSUE THREAD

**Issue by ukmojb** [0999312/TofuCraftReload#112]
#### MOD版本 - Mod version:

TofuCraftReload-0.1.0.9

#### Forge版本 - Forge version:

1.12.2-Forge_14.23.5.2860

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

单人

#### 完整的MOD列表 - Installed mods:

![](在此处填入你的截图链接，没有截图请删除此行 Paste your screenshot link here, or delete this line)
https://pan.baidu.com/s/1rTF3PWwu1fuIb5K05ZTQZg?pwd=r55b
#### 产生Bug的步骤 - How to reproduce:

1.拿着盐卤右键不可交互的方块或空气时，盐卤会直接消失，若还有没堆叠在一起的盐卤，打开背包后，消失的盐卤会出现在鼠标指针上
2.拿着盐卤右键豆浆也时盐卤会消失
3. etc...

#### 反映Bug的图片 - Pictures:

![](在此处填入你的图片链接，没有图片请删除此行 Paste your picture link here, or delete this line)

**Comment by 0999312** [comment]
1.12.2版本这边已经无法更新了，十分抱歉。
至于盐卤的问题，或许你不堆叠使用更合适一些。
