### ISSUE TITLE
[Request][请求]  New Village Generation cfg    添加村庄生成配置

### ISSUE THREAD

**Issue by chenming0v0** [0999312/TofuCraftReload#113]
我是一名modpack作者，我想用rec来修改村庄的生成，但在那之前我要把所以额外添加村庄建筑生成的mod全部关掉，但在关闭TofuCraftReload   mod添加的建筑时，发现没有可选的配置文件

I'm a modpack author and I want to use rec to modify the village generation, but before that I have to turn off all the mods that add extra village buildings to the generation, but when I turn off the buildings added by the TofuCraftReload mod, I find that there is no optional profile
Sorry if I said anything stupid, it's because of my region, I'm from China

**Comment by 0999312** [comment]
说一下Minecraft版本

**Comment by chenming0v0** [comment]
原来是中国人啊，
版本是1.12.2

**Comment by chenming0v0** [comment]
您好还在吗？

**Comment by 0999312** [comment]
1.12.2目前无法更新，无法修复，非常抱歉。
