### ISSUE TITLE
Caught exception from TofuCraftReload (tofucraft)

### ISSUE THREAD

**Issue by mem0rz** [0999312/TofuCraftReload#24]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3685.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/1/19 4:36 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TofuCraftReload (tofucraft)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer
	at cn.mcmod.tofucraft.CommonProxy.init(CommonProxy.java:49)
	at cn.mcmod.tofucraft.TofuMain.init(TofuMain.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@7bbbb6a8 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class buo for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjo000(MinecraftServer.java:3975)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjo000(MinecraftServer.java:3975)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-8-amd64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4072022656 bytes (3883 MB) / 5363990528 bytes (5115 MB) up to 5363990528 bytes (5115 MB)
	JVM Flags: 3 total; -Xmx5500M -Xms5500M -XX:MaxPermSize=128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                                      | Signature                                |
	|:----- |:--------------------- |:------------------------ |:----------------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft             | 1.12.2                   | minecraft.jar                                               | None                                     |
	| LCHI  | mcp                   | 9.42                     | minecraft.jar                                               | None                                     |
	| LCHI  | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2836-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                 | 14.23.5.2836             | forge-1.12.2-14.23.5.2836-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | advancedrocketrycore  | 1                        | minecraft.jar                                               | None                                     |
	| LCHI  | spongeapi             | 7.1.0-4ab0d1a5           | spongeforge-1.12.2-2768-7.1.6-RC3685.jar                    | None                                     |
	| LCHI  | sponge                | 1.12.2-7.1.6-SNAPSHOT    | spongeforge-1.12.2-2768-7.1.6-RC3685.jar                    | None                                     |
	| LCHI  | spongeforge           | 1.12.2-2768-7.1.6-RC3685 | spongeforge-1.12.2-2768-7.1.6-RC3685.jar                    | None                                     |
	| LCHI  | foamfixcore           | 7.7.4                    | minecraft.jar                                               | None                                     |
	| LCHI  | ic2                   | 2.8.135-ex112            | industrialcraft-2-2.8.135-ex112.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | libvulpes             | 0.4.0.-54                | LibVulpes-1.12.2-0.4.0-54-universal.jar                     | None                                     |
	| LCHI  | advancedrocketry      | 1.5.0.-139               | AdvancedRocketry-1.12.2-1.5.0-139-universal.jar             | None                                     |
	| LCHI  | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                                      | None                                     |
	| LCHI  | biomesoplenty         | 7.0.1.2427               | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar               | None                                     |
	| LCHI  | codechickenlib        | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | redstoneflux          | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHI  | brandonscore          | 2.4.10                   | BrandonsCore-1.12.2-2.4.10.198-universal(1).jar             | None                                     |
	| LCHI  | buildinggadgets       | 2.6.8                    | BuildingGadgets-2.6.8.jar                                   | None                                     |
	| LCHI  | chinjufumod           | 3.2.2                    | ChinjufuMod[1.12.2]3.2.2.jar                                | None                                     |
	| LCHI  | extendedrenderer      | v1.0                     | coroutil-1.12.1-1.2.31.jar                                  | None                                     |
	| LCHI  | coroutil              | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                                  | None                                     |
	| LCHI  | configmod             | v1.0                     | coroutil-1.12.1-1.2.31.jar                                  | None                                     |
	| LCHI  | crafttweaker          | 4.1.17                   | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LCHI  | jei                   | 4.15.0.278               | jei_1.12.2-4.15.0.278.jar                                   | None                                     |
	| LCHI  | crafttweakerjei       | 2.0.3                    | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LCHI  | draconicevolution     | 2.3.21                   | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar          | None                                     |
	| LCHI  | foamfix               | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                                   | None                                     |
	| LCHI  | cfm                   | 6.2.0                    | furniture-6.2.0-1.12.2.jar                                  | None                                     |
	| LCHI  | gravisuite            | 3.1.1                    | Gravitation+Suite-3.1.1.jar                                 | None                                     |
	| LCHI  | journeymap            | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                                 | None                                     |
	| LCHI  | lostcities            | 2.0.17                   | lostcities-1.12-2.0.17.jar                                  | None                                     |
	| LCHI  | megamenus             | 0.3                      | Mega Menus-0.3.jar                                          | None                                     |
	| LCHI  | mekanism              | 1.12.2-9.7.2.373         | Mekanism-1.12.2-9.7.2.373.jar                               | None                                     |
	| LCHI  | mekanismgenerators    | 1.12.2-9.7.2.373         | MekanismGenerators-1.12.2-9.7.2.373.jar                     | None                                     |
	| LCHI  | nei                   | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | harvestcraft          | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar | None                                     |
	| LCHI  | railcraft             | 12.0.0                   | railcraft-12.0.0.jar                                        | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHI  | flammpfeil.slashblade | mc1.12-r22               | SlashBlade-mc1.12-r22.jar                                   | None                                     |
	| LCHI  | slashblade_addon      | 1.1.0                    | SJAP-1.1.0.jar                                              | None                                     |
	| LCHI  | teastory              | 3.3.1-B30.413-1.12.2     | TeaStory-3.3.1-B30.413-1.12.2.jar                           | None                                     |
	| LCHE  | tofucraft             | 0.0.4                    | TofuCraftReload-0.0.4.jar                                   | None                                     |
	| LCH   | bspkrscore            | at_0.9                   | TreeCapitator-Mod-1.12.jar                                  | None                                     |
	| LCH   | treecapitator         | at_0.9                   | TreeCapitator-Mod-1.12.jar                                  | None                                     |
	| LCH   | twilightforest        | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar                 | None                                     |
	| LCH   | of                    | 0.13                     | Useful+Interior+-+0.13+[1.12.2].jar                         | None                                     |
	| LCH   | vanilladeathchest     | 1.12.2-1.8.0.2           | vanilladeathchest-1.12.2-1.8.0.2.jar                        | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCH   | wawla                 | 2.5.269                  | Wawla-1.12.2-2.5.269.jar                                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | zombie_players        | 1.12.1-1.2.7             | zombie_players-1.12.1-1.2.7.jar                             | None                                     |
	| LCH   | zombieawareness       | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar                          | None                                     |
	| LCH   | commandsigns          | 2.10                     | commandsigns-2.10.jar                                       | None                                     |
	| LCH   | worldedit             | 6.1.9-SNAPSHOT           | 【P】[创世神]worldedit-sponge-6.1.9-SNAPSHOT-dist.jar            | None                                     |
	| LCH   | langswitch            | 1.4                      | LangSwitch-1.4.jar                                          | None                                     |
	| LCH   | luckperms             | 4.2.17                   | 【P】[权限管理]LuckPerms-Sponge-4.2.17.jar                        | None                                     |
	| LCH   | serverlistplus        | 3.4.7                    | ServerListPlus-3.4.7-Universal.jar                          | None                                     |
	| LCH   | pjc                   | 0.4.0-unstable           | projectcore-7.2.0-0.4.0-unstable.jar                        | None                                     |
	| LCH   | stackban              | 0.3.0                    | stackban-7.1.0-0.3.0.jar                                    | None                                     |
	| LCH   | griefprevention       | 1.12.2-4.3.0.689         | griefprevention-1.12.2-4.3.0.689.jar                        | None                                     |
	| LCH   | carrotshop            | 1.16-S7.0-MC1.12.2       | CarrotShop-1.16-S7.0-MC1.12.2.jar                           | None                                     |
	| LCH   | economylite           | 2.14.3                   | 【P】[经济]EconomyLite-7.1.0-2.14.3.jar                         | None                                     |
	| LCH   | flexiblelogin         | 0.17.4                   | flexiblelogin-0.17.4.jar                                    | None                                     |
	| LCH   | universalmarket       | 1.3                      | UniversalMarket-1.12.2-v1.3.jar                             | None                                     |
	| LCH   | placeholderapi        | 4.4                      | PlaceholderAPI-4.4.jar                                      | None                                     |
	| LCH   | virtualchest          | 1.0.0-beta-6             | 【P】[菜单]VirtualChest-1.0.0-beta-6.jar                        | None                                     |
	| LCH   | kickafkplayer         | 0.1.0                    | KickAFKPlayer-0.1.0.jar                                     | None                                     |
	| LCH   | nucleus               | 1.4.3-S7.0               | 【P】[前置]Nucleus-1.4.3-S7.0-MC1.12.2-plugin.jar               | None                                     |
	| LCH   | karoglansigneditor    | 3.4.1                    | 【P】[牌子编辑器]KaroglanSignEditor-3.4.1.jar                      | None                                     |
	| LCH   | vshop                 | 2.0                      | VillagerShops-2.0.jar                                       | None                                     |
	| LCH   | catclearlag           | 0.9.0                    | CatClearLag-0.9.0.jar                                       | None                                     |
	| LCH   | immersiveengineering  | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | coffeework            | @version@                | CoffeeWorkshop_V1.2.5_MC1.12.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3685.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by cybmp3** [comment]
0.3

**Comment by mem0rz** [comment]
0.3 is ok.
0.4report crash

**Comment by 0999312** [comment]
马上就开始修。

**Comment by 0999312** [comment]
马上发布修复版本，请稍等

**Comment by 0999312** [comment]
Fixed in v0.0.4.1
