### ISSUE TITLE
Crash w/ Underground Biomes

### ISSUE THREAD

**Issue by WenXin20** [0999312/TofuCraftReload#29]
Minecraft v1.12.2
Forge v14.23.5.2838
Tofucraft Reloaded v0.0.5
[Underground Biomes](https://minecraft.curseforge.com/projects/underground-biomes) v1.3.5

I got a crash with the new version of Tofucraft when I tried to open my world. 
Edit: Underground Biomes seems to be involved with the crash.
Here's a [crash report.](https://gist.github.com/WenXin20/fdcaa1a174ac4c4c47976ae840cbd0a8)

**Comment by 0999312** [comment]
Fixed in newest version.
