### ISSUE TITLE
Crash when connecting the EnderIO conduit to a salt furnace.

### ISSUE THREAD

**Issue by myaako-wasure** [0999312/TofuCraftReload#36]
https://pastebin.com/ypiMJhHu

製塩かまどにEnderIOの導管を接続して空き瓶を突っ込むとクラッシュします。

Crash when connecting a conduit of EnderIO to a salt furnace and inserting an empty bottle.

**Comment by Prunoideae** [comment]
Fixed in the recent commit through clearing and rewriting the errored code.
