### ISSUE TITLE
【备忘】豆腐能存储器的GUI名称显示异常问题

### ISSUE THREAD

**Issue by RisingInIris2017** [0999312/TofuCraftReload#72]
![](https://s2.ax1x.com/2019/11/12/Mlgqe0.jpg)
如图，豆腐能存储器在lang文件中的注册名和游戏中豆腐能存储器GUI上的显示名完全相同，
但游戏中不显示本地化名称。
目前原因不明，有待解决，发这条issue作为备忘。

**Comment by 0999312** [comment]
FIXED
