### ISSUE TITLE
豆腐能机器工作时闪烁

### ISSUE THREAD

**Issue by RisingInIris2017** [0999312/TofuCraftReload#90]
#### MOD版本 - Mod version:

TofuCraftReload-0.1.0.5.1

#### Forge版本 - Forge version:

forge-1.12.2-14.23.5.2847

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

Both Singleplayer and Multiplayer

#### 完整的MOD列表 - Installed mods:

![TIM截图20200131092445](https://user-images.githubusercontent.com/28519848/73504805-8da5be00-440b-11ea-82bc-fdec51738e2e.png)

## 问题描述 - Description of the problem
如 issue 标题所述。
会出现闪烁现象的机器，目前已知有以下几个：
豆腐能聚合器、高级豆腐能聚合器、豆腐能储存器。

**Comment by Prunoideae** [comment]
修了。
